variable "aws_bucket_consul_license_arn" {
  type        = string
  description = "ARN of S3 bucket with Consul license"
}

variable "kms_key_arn" {
  type        = string
  description = "KMS Key ARN used for S3 bucket encryption"
}

variable "resource_name_prefix" {
  type        = string
  description = "Resource name prefix used for tagging and naming AWS resources"
}

variable "secrets_manager_arn_acl_token_server" {
  type        = string
  description = "Secrets manager ARN where Consul server default ACL token is stored"
}

variable "secrets_manager_arn_gossip" {
  type        = string
  description = "Secrets manager ARN where gossip encryption key is stored"
}

variable "secrets_manager_arn_tls" {
  type        = string
  description = "Secrets manager ARN where TLS cert info is stored"
}

variable "user_supplied_iam_role_name_server" {
  type        = string
  description = "(OPTIONAL) User-provided IAM role name for Consul servers. This will be used for the instance profile provided to the AWS launch configuration. The minimum permissions must match the defaults generated by the IAM submodule for cloud auto-join, secrets manager access, and KMS"
  default     = null
}

