variable "aws_bucket_consul_license_arn" {
  type        = string
  description = "ARN of S3 bucket with Consul license"
}

variable "aws_bucket_consul_license" {
  type        = string
  description = "S3 bucket ID containing Consul license"
}

variable "aws_region" {
  type        = string
  description = "AWS region where Consul is being deployed"
}

variable "ca_cert" {
  type        = string
  description = "Certificate Authority public cert that was used to sign servers certs. This is required for auto_encrypt to work on the clients"
}

variable "client_count" {
  type        = number
  description = "Number of Consul clients to deploy in ASG"
  default     = 3
}

variable "common_tags" {
  type        = map(string)
  description = "(Optional) Map of common tags for all taggable AWS resources."
  default     = {}
}

variable "consul_license_name" {
  type        = string
  description = "The file name for the Consul license file as it will be stored in S3"
  default     = "consul.hclic"
}

variable "consul_sg_id" {
  type        = string
  description = "Security group ID that should be provided to Consul clients"
}

variable "consul_subnets" {
  type        = list(string)
  description = "Private subnets where Consul will be deployed"
}

variable "consul_version" {
  type        = string
  default     = "1.10.3"
  description = "Consul version"
}

variable "instance_type" {
  type        = string
  description = "EC2 instance type"
  default     = "m5.xlarge"
}

variable "key_name" {
  type        = string
  description = "key pair to use for SSH access to instance"
  default     = null
}

variable "kms_key_arn_s3_bucket" {
  type        = string
  description = "KMS Key ID used in the main module for S3 bucket containing Consul license"
}

variable "kms_key_arn_secrets_manager" {
  type        = string
  description = "Specifies the ARN or ID of the AWS KMS customer master key (CMK) to be used to encrypt the secret values in the versions stored in this secret. If you don't specify this value, then Secrets Manager defaults to using the AWS account's default CMK (the one named aws/secretsmanager"
  default     = null
}

variable "recovery_window" {
  type        = number
  description = "Specifies the number of days that AWS Secrets Manager waits before it can delete the secret"
  default     = 0
}

variable "resource_name_prefix" {
  type        = string
  description = "Resource name prefix used for tagging and naming AWS resources"
}

variable "secrets_manager_arn_gossip" {
  type        = string
  description = "Secrets manager ARN where gossip encryption key is stored"
}

variable "tags" {
  type        = map(string)
  description = "Tags for secrets manager secret"
  default = {
    Consul = "secret-data"
  }
}

variable "user_supplied_ami_id" {
  type        = string
  description = "AMI ID to use with Consul clients"
  default     = null
}

variable "user_supplied_iam_role_name_client" {
  type        = string
  description = "(OPTIONAL) User-provided IAM role name for Consul clients. This will be used for the instance profile provided to the AWS launch configuration. The minimum permissions must match the defaults generated by the IAM submodule for cloud auto-join, secrets manager access, and KMS"
  default     = null
}

variable "user_supplied_userdata_path_client" {
  type        = string
  description = "(Optional) File path to custom userdata script for Consul clients being supplied by the user"
  default     = null
}

variable "vpc_id" {
  type        = string
  description = "VPC ID where Consul will be deployed"
}
